service: auth
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
    JWT_SECRET: 'rede-secret'
    API_DOMAIN: "api.${ssm:/primary_domain_name}"

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "auth"
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest

functions:

  register:
    timeout: 30
    handler: index.register
    logRetentionInDays: 7
    events:
      - http:
          path: /register
          method: post
          cors: 
            origin: '*'
            headers: '*'
  magic:
    timeout: 30
    handler: index.magicLinkLogin
    logRetentionInDays: 7
    events:
      - http:
          path: /magic
          method: post
          cors: 
            origin: '*'
            headers: '*'

  magicLink:
    timeout: 30
    handler: index.requestMagicLink
    logRetentionInDays: 7
    events:
      - http:
          path: /magic-link
          method: post
          cors: 
            origin: '*'
            headers: '*'
  

  login:
    timeout: 30
    handler: index.login
    logRetentionInDays: 7
    events:
      - http:
          path: /login
          method: post
          cors: 
            origin: '*'
            headers: '*'

  me:
    timeout: 30
    handler: index.me
    logRetentionInDays: 7
    events:
      - http:
          path: /me
          method: get
          authorizer: verify-token
          cors: 
            origin: '*'
            headers: '*'

  verify-token:
    handler: index.verify_token
    logRetentionInDays: 7

    


