service: fetch
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
    REDDIT_CLIENT_ID: ${ssm:/reddit_client_id}
    REDDIT_SECRET_KEY: ${ssm:/reddit_secret_key}
    REDDIT_USERNAME: ${ssm:/reddit_username}
    REDDIT_PASSWORD: ${ssm:/reddit_password}
    API_DOMAIN: "api.${ssm:/primary_domain_name}"

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "fetch"
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  authorizerARN: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-${sls:stage}-verify-token"

functions:
  fetchRedditPosts:
    timeout: 30
    handler: index.fetch_reddit_posts
    logRetentionInDays: 30
    events:
      - http:
          path: /reddit/posts
          method: post
          cors: 
            origin: '*'
            headers: '*'
  fetchRSS:
    timeout: 900
    handler: rss.fetch_rss_data
    logRetentionInDays: 30
    events:
      - http:
          path: /rss/data
          method: post
          cors: 
            origin: '*'
            headers: '*'

  fetchSearchResult:
    timeout: 900
    handler: context.fetch_search_result
    logRetentionInDays: 30
    events:
      - http:
          path: /search/result
          method: post
          cors: 
            origin: '*'
            headers: '*'