service: email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"


plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "email"
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest

functions:
  sendEmails:
    timeout: 30
    handler: index.send_emails
    logRetentionInDays: 30
    events:
      - http:
          path: /send
          method: post
          cors: 
            origin: '*'
            headers: '*'