service: email
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
    SENDGRID_API_KEY: ${ssm:/sendgrid_api_key}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "*"


plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "email"
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  authorizerARN: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-${sls:stage}-verify-token"

functions:
  sendEmails:
    timeout: 30
    handler: index.send_email
    logRetentionInDays: 30
    events:
      - http:
          path: /send
          method: post
          cors: 
            origin: '*'
            headers: '*'

  verifyEmail:
    timeout: 30
    handler: index.verify_email
    logRetentionInDays: 30
    events:
      - http:
          path: /verify_email_address
          method: post
          cors:
            origin: '*'
            headers: '*'