service: ai
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    MONGO_CONNECTION_STRING: ${ssm:/primary_db_connection_string}
    OPENAI_API_KEY: ${ssm:/openai_api_key}


plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: "api.${ssm:/primary_domain_name}"
    certificateArn: ${ssm:/primary_domain_cert_arn}
    basePath: "ai"
    endpointType: 'regional'
    securityPolicy: tls_1_2
    apiType: rest
  authorizerARN: "arn:aws:lambda:${aws:region}:${aws:accountId}:function:auth-${sls:stage}-verify-token"

functions:

  contentFromTemplate:
    timeout: 30
    handler: index.content_from_template
    logRetentionInDays: 30
    events:
      - http:
          path: /content-from-template
          method: post
          cors: 
            origin: '*'
            headers: '*'
  summarize:
    timeout: 30
    handler: index.summarize
    logRetentionInDays: 30
    events:
      - http:
          path: /summarize
          method: post
          cors: 
            origin: '*'
            headers: '*'